# -*- coding: utf-8 -*-
"""Air_Quality_Measures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd26XgcdHrq3tu1vmLY4E7aYh3SPQ2Fd
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_air = pd.read_csv('/content/drive/MyDrive/Air_Quality_Measures_on_the_National_Environmental_Health_Tracking_Network.csv')

df_air.head()

clean_air = df_air[[
    "MeasureId", "MeasureName", "MeasureType",
    "StateName", "CountyName", "ReportYear", "Value"
]]

clean_file_path = "/content/drive/MyDrive/Air_Quality_Measures_on_the_National_Environmental_Health_Tracking_Network (1).csv"
clean_air.to_csv(clean_file_path, index=False)

clean_file_path

df_air.isnull()

yearly_avg_value = df_air.groupby('ReportYear')['Value'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=yearly_avg_value, x='ReportYear', y='Value')
plt.title('Average Air Quality Measure Value Over Years')
plt.xlabel('Report Year')
plt.ylabel('Average Value')
plt.grid(True)
plt.savefig('average_value_over_years.png')
plt.close()

avg_value_by_measure = df_air.groupby('MeasureName')['Value'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.scatterplot(data=df_air, x='ReportYear', y='Value', alpha=0.6)
plt.title('Air Quality Measure Values Over Years')
plt.xlabel('Report Year')
plt.ylabel('Value')
plt.grid(True)
plt.show()

avg_value_by_state = df_air.groupby('StateName')['Value'].mean().reset_index()
top_10_states = avg_value_by_state.sort_values(by='Value', ascending=False).head(10)

plt.figure(figsize=(12, 7))
sns.barplot(data=top_10_states, x='Value', y='StateName', palette='viridis')
plt.title('Top 10 States by Average Air Quality Measure Value')
plt.xlabel('Average Value')
plt.ylabel('State Name')
plt.tight_layout()
plt.savefig('top_10_states_by_avg_value.png')
plt.close()

selected_measure_name = "Number of days with maximum 8-hour average ozone concentration over the National Ambient Air Quality Standard"
df_filtered_measure = df_air[df_air['MeasureName'] == selected_measure_name].copy()
display(df_filtered_measure.head())

yearly_avg_measure_value = df_filtered_measure.groupby('ReportYear')['Value'].mean().reset_index()
display(yearly_avg_measure_value.head())

plt.figure(figsize=(12, 6))
sns.lineplot(data=yearly_avg_measure_value, x='ReportYear', y='Value')
plt.title('Average Value of Selected Measure Over Time')
plt.xlabel('Report Year')
plt.ylabel('Average Value')
plt.grid(True)
plt.show()

# Calculate descriptive statistics using describe()
desc_stats = df_air['Value'].describe()

# Calculate variance, skewness, and kurtosis separately
variance = df_air['Value'].var()
skewness = df_air['Value'].skew()
kurtosis = df_air['Value'].kurtosis()

# Display all the calculated statistics
print("Descriptive Statistics for 'Value' column:")
display(desc_stats)
print(f"\nVariance: {variance}")
print(f"Skewness: {skewness}")
print(f"Kurtosis: {kurtosis}")

df_modeling = df_air[['ReportYear', 'Value']].copy()
df_modeling = df_modeling.groupby('ReportYear')['Value'].mean().reset_index()
df_modeling.rename(columns={'Value': 'AverageValue'}, inplace=True)
display(df_modeling.head())

X = df_modeling[['ReportYear']]
y = df_modeling['AverageValue']

display(top_10_states)
display(bottom_10_states)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error, r2_score

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

df_modeling['PredictedValue'] = model.predict(df_modeling[['ReportYear']])
display(df_modeling.head())

print("Top 10 States by Average Air Quality Measure Value:")
display(top_10_states)

print("Bottom 10 States by Average Air Quality Measure Value:")
display(bottom_10_states)